<#
setup_keys.ps1

One-time setup script that prompts for API keys and stores them safely:
- Sets user-level Windows environment variables (recommended) so .bat files work.
- Writes local helper files set_env.ps1 (gitignored) as a fallback.

This script never prints your keys.

Run by double-clicking setup_keys.bat (recommended), or from PowerShell:
  powershell -NoProfile -ExecutionPolicy Bypass -File .\setup_keys.ps1
#>

$ErrorActionPreference = 'Stop'

function ConvertFrom-SecureStringPlainText {
    param([Parameter(Mandatory=$true)][Security.SecureString]$Secure)
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    }
    finally {
        if ($bstr -ne [IntPtr]::Zero) {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        }
    }
}

function Read-ApiKey {
    param(
        [Parameter(Mandatory=$true)][string]$Name,
        [Parameter(Mandatory=$true)][string]$EnvVar,
        [Parameter(Mandatory=$true)][string]$HelpUrl
    )

    Write-Host "" 
    Write-Host "=== $Name ==="
    Write-Host "If you do not have a key yet, open: $HelpUrl"
    Write-Host "Paste the key when prompted. It will NOT be shown on screen." 

    $secure = Read-Host -Prompt "Paste $Name key (or press Enter to skip)" -AsSecureString
    $plain = ConvertFrom-SecureStringPlainText -Secure $secure
    if ($null -eq $plain) { $plain = '' }
    $plain = $plain.Trim()

    if ([string]::IsNullOrWhiteSpace($plain)) {
        return @{ Provided = $false; Value = '' }
    }

    return @{ Provided = $true; Value = $plain }
}

function Write-SetEnvFile {
    param(
        [Parameter(Mandatory=$true)][string]$FilePath,
        [Parameter(Mandatory=$true)][hashtable]$Vars
    )

    $lines = @(
        '# Auto-generated by setup_keys.ps1',
        '# This file contains secrets. DO NOT share it.',
        '# This file is gitignored and should not be committed.',
        ''
    )

    foreach ($kvp in $Vars.GetEnumerator()) {
        $name = $kvp.Key
        $value = $kvp.Value
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            # Use single quotes in PowerShell to avoid escaping most characters.
            $escaped = $value.Replace("'", "''")
            $lines += ('$Env:' + $name + " = '$escaped'")
        }
    }

    $dir = Split-Path -Parent $FilePath
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }

    $lines | Out-File -LiteralPath $FilePath -Encoding UTF8 -Force
}

Write-Host ""
Write-Host "API Key Setup"
Write-Host "============="
Write-Host "This will configure your keys so you can run the tools without editing code."

$toolsRoot = $PSScriptRoot
$voiceoverDir = Join-Path $toolsRoot 'voiceover'
$langDetectDir = Join-Path $toolsRoot 'Language Detection'

$eleven = Read-ApiKey -Name 'ElevenLabs' -EnvVar 'ELEVENLABS_API_KEY' -HelpUrl 'https://elevenlabs.io/'
$deepl  = Read-ApiKey -Name 'DeepL' -EnvVar 'DEEPL_API_KEY' -HelpUrl 'https://www.deepl.com/account'

if (-not $eleven.Provided -and -not $deepl.Provided) {
    Write-Host "" 
    Write-Host "No keys were provided. Nothing to do." 
    Write-Host "You can run this again anytime." 
    exit 0
}

Write-Host ""
$remember = Read-Host "Should Windows remember these keys for you? Recommended: Y (press Enter for Yes) [Y/n]"
if ([string]::IsNullOrWhiteSpace($remember) -or $remember.Trim().ToLower() -eq 'y' -or $remember.Trim().ToLower() -eq 'yes') {
    if ($eleven.Provided) {
        [Environment]::SetEnvironmentVariable('ELEVENLABS_API_KEY', $eleven.Value, 'User')
        $Env:ELEVENLABS_API_KEY = $eleven.Value
    }
    if ($deepl.Provided) {
        [Environment]::SetEnvironmentVariable('DEEPL_API_KEY', $deepl.Value, 'User')
        $Env:DEEPL_API_KEY = $deepl.Value
    }
    Write-Host "Saved keys to your Windows user environment variables." 
    Write-Host "Note: You may need to close/reopen terminals for other windows to see them." 
} else {
    # Only set for current session.
    if ($eleven.Provided) { $Env:ELEVENLABS_API_KEY = $eleven.Value }
    if ($deepl.Provided)  { $Env:DEEPL_API_KEY = $deepl.Value }
    Write-Host "Keys set for this PowerShell window only." 
}

# Always write local helper files as a fallback (gitignored).
if ($eleven.Provided) {
    $voiceoverSetEnv = Join-Path $voiceoverDir 'set_env.ps1'
    Write-SetEnvFile -FilePath $voiceoverSetEnv -Vars @{ 'ELEVENLABS_API_KEY' = $eleven.Value }
}
if ($deepl.Provided) {
    $langSetEnv = Join-Path $langDetectDir 'set_env.ps1'
    Write-SetEnvFile -FilePath $langSetEnv -Vars @{ 'DEEPL_API_KEY' = $deepl.Value }
}

Write-Host ""
Write-Host "Setup complete."
Write-Host "Next steps:" 
Write-Host "- Voiceover: run voiceover\\run.bat" 
Write-Host "- Language detection: run Language Detection\\run.bat" 
Write-Host ""
